
from typing import AsyncGenerator, List, Protocol

from common import GeocodedLocation


class BulkAsyncGeocoder(Protocol):
    def __init__(self, rate_limit: int = 2): ...
    async def geocode_async_gen(self, addresses: List[str], in_order=True) -> AsyncGenerator[GeocodedLocation, None]: ...


class AsyncGeocoder(Protocol):
    def __init__(self, rate_limit: int = 2): ...
    async def geocode(self, address: str) -> GeocodedLocation: ...
    async def geocode_with_client(self, address: str, client) -> GeocodedLocation: ...
